server:
  port: 8001
spring:
  application:
    name: cloud-provider-hystrix-payment
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      集群
#      defaultZone: http://eureka5001.com:5001/eureka,http://eureka5002.com:5002/eureka
      defaultZone: http://eureka5001.com:5001/eureka
